### ISSUE TITLE
Flaky test: MoleculeTest.errorDelayed

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/molecule#45]
```
 app.cash.molecule.MoleculeTest > errorDelayed FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at app.cash.molecule.MoleculeTest.errorDelayed(MoleculeTest.kt:126)
```

**Comment by DSteve595** [comment]
Not sure if this is a clue, but: https://github.com/cashapp/molecule/discussions/64#discussioncomment-1647720
